/**
 * Dieu khoan Thoa thuan hop tac KOL/KOC ShopTik (tu
 * Thoa_thuan_hop_tac_KOL_KOC_ShopTik_V2.docx). Hien thi o buoc 1 dang ky KOL/KOC.
 */
export const KOL_AGREEMENT_VERSION = 2;

export const KOL_AGREEMENT_PARAGRAPHS: readonly string[] = [
  "CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM",
  "Độc lập - Tự do - Hạnh phúc",
  "THỎA THUẬN HỢP TÁC KOL/KOC",
  "VÀ CAM KẾT BẢO MẬT THÔNG TIN",
  "Số: ……/2026/HT-KOLKOC",
  "Căn cứ:",
  "Bộ luật Dân sự số 91/2015/QH13 và các văn bản sửa đổi, hướng dẫn có liên quan;",
  "Luật Thương mại số 36/2005/QH11 và các văn bản sửa đổi, hướng dẫn có liên quan;",
  "Luật Quảng cáo số 16/2012/QH13, được sửa đổi, bổ sung bởi Luật số 75/2025/QH15 (có hiệu lực từ ngày 01/01/2026);",
  "Luật Bảo vệ quyền lợi người tiêu dùng số 19/2023/QH15 và các văn bản hướng dẫn;",
  "Luật Bảo vệ dữ liệu cá nhân số 91/2025/QH15 và Nghị định số 356/2025/NĐ-CP (có hiệu lực từ ngày 01/01/2026);",
  "Luật Thương mại điện tử số 122/2025/QH15 và Nghị định số 248/2026/NĐ-CP (có hiệu lực từ ngày 01/07/2026);",
  "Nhu cầu và khả năng hợp tác của các Bên.",
  "Hôm nay, ngày …… tháng …… năm 2026, các Bên gồm:",
  "BÊN A – ĐƠN VỊ VẬN HÀNH NỀN TẢNG/ỨNG DỤNG SHOPTIK",
  "Tên pháp nhân",
  "[TÊN CÔNG TY/PHÁP NHÂN]",
  "Mã số thuế",
  "[……………………]",
  "Địa chỉ trụ sở",
  "[……………………]",
  "Đại diện",
  "[……………………]",
  "Chức vụ",
  "[……………………]",
  "Điện thoại / Email",
  "[……………………]",
  "Tên nền tảng",
  "ShopTik",
  "BÊN B – KOL/KOC/ĐỐI TÁC TIẾP THỊ LIÊN KẾT",
  "Họ và tên",
  "[……………………]",
  "Ngày sinh",
  "[……………………]",
  "Số CCCD/Thẻ căn cước",
  "[……………………]",
  "Ngày cấp / Nơi cấp",
  "[……………………]",
  "Địa chỉ liên hệ",
  "[……………………]",
  "Điện thoại",
  "[……………………]",
  "Email",
  "[……………………]",
  "Mã số thuế cá nhân",
  "[……………………]",
  "Tài khoản ngân hàng",
  "[……………………]",
  "Chủ tài khoản / Ngân hàng",
  "[……………………]",
  "Bên A và Bên B sau đây gọi riêng là “Bên” và gọi chung là “Các Bên”. Các Bên thống nhất ký kết Thỏa thuận với các điều khoản sau:",
  "ĐIỀU 1. GIẢI THÍCH THUẬT NGỮ",
  "“Nền tảng” là ứng dụng/website ShopTik do Bên A sở hữu, vận hành hoặc được quyền khai thác để cung cấp công cụ tiếp thị liên kết, theo dõi đơn hàng, đối soát và thanh toán hoa hồng.",
  "“KOL/KOC” là Bên B trực tiếp tạo, đăng tải hoặc chuyển tải nội dung giới thiệu/quảng cáo sản phẩm, dịch vụ trên mạng xã hội, nền tảng số hoặc các kênh truyền thông khác.",
  "“Liên kết tiếp thị liên kết” (affiliate link) là đường dẫn, mã, deeplink hoặc cơ chế theo dõi do Bên A/đối tác của Bên A cung cấp để ghi nhận nguồn giới thiệu.",
  "“Đơn hàng hợp lệ” là đơn hàng được hệ thống/đối tác liên kết ghi nhận, đã hoàn tất điều kiện thanh toán, không bị hủy/hoàn/trả, không gian lận và đã qua thời hạn đối soát theo chính sách áp dụng.",
  "“Thông tin mật” là mọi thông tin chưa công khai liên quan đến Bên A, Nền tảng, công nghệ, dữ liệu, chính sách hoa hồng, chiến dịch, khách hàng, đối tác, tài liệu nội bộ, số liệu kinh doanh và bí mật thương mại.",
  "“Dữ liệu cá nhân” bao gồm thông tin định danh, liên hệ, tài khoản mạng xã hội, thông tin thanh toán/thuế, hình ảnh CCCD/Thẻ căn cước và video khuôn mặt dùng cho xác minh danh tính.",
  "ĐIỀU 2. PHẠM VI VÀ NGUYÊN TẮC HỢP TÁC",
  "Bên B tham gia chương trình KOL/KOC/tiếp thị liên kết của Bên A trên cơ sở độc lập, tự chịu trách nhiệm về nội dung mình tạo ra, trừ nội dung do Bên A cung cấp nguyên văn hoặc phê duyệt bằng văn bản/qua hệ thống.",
  "Bên B có thể tạo video, bài viết, livestream, bài đăng, story, short video hoặc hình thức nội dung khác để giới thiệu sản phẩm/dịch vụ và gắn affiliate link/mã theo quy định của Bên A.",
  "Thỏa thuận này không mặc nhiên tạo quan hệ lao động, đại lý độc quyền, liên doanh, ủy quyền đại diện pháp luật hoặc quyền nhân danh Bên A để cam kết với bên thứ ba.",
  "Hợp tác mặc định là không độc quyền. Điều kiện độc quyền, nếu có, phải được ghi rõ tại Phụ lục/Đơn đặt hàng chiến dịch hoặc thỏa thuận riêng.",
  "ĐIỀU 3. HỒ SƠ ĐĂNG KÝ VÀ XÁC MINH KOL/KOC",
  "3.1. Trước khi được kích hoạt tài khoản đối tác hoặc nhận thanh toán, Bên B phải cung cấp đầy đủ, trung thực và cập nhật hồ sơ xác minh theo Phụ lục 01 của Thỏa thuận này.",
  "03 đường dẫn tài khoản/kênh đang sử dụng: TikTok, Facebook và YouTube (ghi đúng URL công khai và tên tài khoản/kênh).",
  "Ảnh chụp rõ nét 02 mặt CCCD/Thẻ căn cước còn giá trị sử dụng; không che thông tin cần thiết cho việc xác minh trừ khi Bên A cho phép.",
  "01 video ngắn quay rõ khuôn mặt để xác minh người đăng ký là chủ thể của giấy tờ và tài khoản hợp tác. Khuyến nghị thời lượng 5–15 giây, khuôn mặt nhìn rõ, không dùng filter che mặt; Bên A có thể yêu cầu Bên B đọc câu xác nhận và ngày đăng ký để chống giả mạo.",
  "Thông tin tài khoản ngân hàng, mã số thuế và thông tin khác cần thiết cho đối soát, thanh toán hoặc thực hiện nghĩa vụ pháp lý.",
  "3.2. Bên A có quyền yêu cầu xác minh bổ sung khi có dấu hiệu thông tin không khớp, tài khoản bị chiếm quyền, nghi ngờ gian lận hoặc theo yêu cầu của cơ quan có thẩm quyền. Việc từ chối cung cấp thông tin cần thiết có thể dẫn đến tạm dừng kích hoạt hoặc thanh toán cho đến khi xác minh hoàn tất.",
  "ĐIỀU 4. QUYỀN VÀ NGHĨA VỤ CỦA BÊN B (KOL/KOC)",
  "Bảo đảm tài khoản/kênh đăng ký thuộc quyền sở hữu, quản lý hợp pháp của Bên B hoặc Bên B có đầy đủ quyền sử dụng để đăng nội dung thương mại.",
  "Cung cấp thông tin trung thực; không giả mạo danh tính, số liệu người theo dõi, lượt xem, tương tác hoặc quyền sở hữu kênh.",
  "Khi nội dung có tính chất quảng cáo/hợp tác thương mại, Bên B phải thông báo rõ cho người xem ngay trước và trong khi quảng cáo bằng dấu hiệu phù hợp (ví dụ: “Quảng cáo”, “Hợp tác trả phí”, “Nội dung tài trợ”, #quangcao) và tuân thủ công cụ gắn nhãn của từng nền tảng.",
  "Trước khi quảng bá, Bên B phải xác minh mức độ tin cậy của bên quảng cáo/người bán và kiểm tra tài liệu sản phẩm mà Bên A cung cấp. Nếu Bên B chưa sử dụng hoặc chưa hiểu rõ sản phẩm/dịch vụ thì không được phát biểu dưới dạng trải nghiệm, xác nhận hoặc khuyến nghị cá nhân như thể đã sử dụng/hiểu rõ.",
  "Không đưa ra tuyên bố sai sự thật, gây nhầm lẫn, phóng đại, cam kết tuyệt đối, công dụng chưa được chứng minh hoặc nội dung vượt quá hồ sơ/chính sách chính thức mà Bên A/người bán cung cấp.",
  "Không quảng bá hàng hóa/dịch vụ bị cấm, hàng giả, hàng xâm phạm quyền sở hữu trí tuệ hoặc chiến dịch mà Bên A đã thông báo dừng.",
  "Tuân thủ pháp luật về quảng cáo, thương mại điện tử, bảo vệ người tiêu dùng, dữ liệu cá nhân, trẻ em, sở hữu trí tuệ, thuế và quy định cộng đồng của TikTok, Facebook, YouTube cùng các nền tảng liên quan.",
  "Chủ động lưu trữ bản gốc nội dung, brief, phê duyệt và bằng chứng đăng tải trong thời gian hợp lý để phục vụ đối soát/khiếu nại.",
  "Không được tự xưng là nhân viên, đại diện pháp luật hoặc người phát ngôn của Bên A nếu không có ủy quyền bằng văn bản.",
  "ĐIỀU 5. HÀNH VI GIAN LẬN VÀ HÀNH VI BỊ CẤM TRONG AFFILIATE",
  "Tự tạo đơn hàng, đơn hàng khống, đơn hàng vòng, sử dụng danh tính/tài khoản thanh toán giả hoặc phối hợp với bên thứ ba nhằm tạo hoa hồng không phát sinh từ giao dịch thực.",
  "Mua traffic giả, click ảo, bot, spam, cookie stuffing, click injection, giả lập thiết bị, sửa tham số tracking hoặc thủ thuật kỹ thuật làm sai lệch nguồn chuyển đổi.",
  "Tự ý thay đổi, che giấu, chuyển hướng affiliate link theo cách vi phạm chính sách của Bên A hoặc của sàn/đối tác liên kết.",
  "Phát tán link hàng loạt vào nhóm/cộng đồng không cho phép quảng cáo, mạo danh thương hiệu, gửi tin nhắn rác hoặc thu thập dữ liệu người dùng trái phép.",
  "Dụ người dùng hủy giao dịch hợp lệ rồi mua lại bằng cơ chế khác nhằm chiếm hoa hồng hoặc gây thiệt hại cho Bên A/đối tác.",
  "Sử dụng nhãn hiệu, logo, giao diện hoặc tài sản của Bên A để lập trang/kênh giả, chạy quảng cáo gây hiểu nhầm rằng tài khoản đó là kênh chính thức.",
  "Khi có căn cứ hợp lý về gian lận, Bên A có quyền tạm giữ khoản thanh toán liên quan, yêu cầu giải trình/chứng từ, loại bỏ giao dịch không hợp lệ và tạm khóa tài khoản trong thời gian xác minh. Bên A phải khôi phục quyền lợi hợp lệ của Bên B nếu kết quả xác minh không phát hiện vi phạm.",
  "ĐIỀU 6. QUYỀN VÀ NGHĨA VỤ CỦA BÊN A",
  "Cung cấp thông tin chiến dịch, chính sách hoa hồng, điều kiện ghi nhận đơn hàng và hướng dẫn sử dụng affiliate link một cách rõ ràng trong phạm vi Bên A kiểm soát.",
  "Cung cấp cho Bên B thông tin/tài liệu sản phẩm do người bán/đối tác cung cấp; thông báo khi có thay đổi quan trọng có thể làm nội dung cũ không còn chính xác.",
  "Vận hành hệ thống theo dõi, đối soát và hỗ trợ Bên B tra cứu kết quả trong phạm vi dữ liệu mà Bên A nhận được từ sàn/đối tác tracking.",
  "Thanh toán hoa hồng hợp lệ theo Điều 7 và chính sách/Phụ lục chiến dịch.",
  "Bảo vệ dữ liệu cá nhân, hồ sơ định danh và Thông tin mật của Bên B theo Điều 10 của Thỏa thuận này.",
  "Không yêu cầu Bên B phát ngôn sai sự thật hoặc đăng nội dung trái pháp luật. Khi có rủi ro pháp lý, Bên A có quyền yêu cầu sửa, ẩn hoặc gỡ nội dung liên quan.",
  "ĐIỀU 7. HOA HỒNG, ĐỐI SOÁT, THANH TOÁN VÀ THUẾ",
  "Mức hoa hồng/tỷ lệ chia sẻ được xác định theo từng chiến dịch, ngành hàng, sàn/đối tác và được Bên A công bố trên Nền tảng hoặc tại Phụ lục. Trường hợp Bên B được hưởng một tỷ lệ phần trăm (%) trên khoản hoa hồng, doanh thu chia sẻ hoặc lợi ích kinh tế mà Bên A nhận từ sàn/đối tác, cơ sở tính phần chia cho Bên B là khoản đủ điều kiện sau đối soát và sau khi trừ các khoản thuế, phí, hoàn trả, điều chỉnh hoặc nghĩa vụ tài chính bắt buộc liên quan trực tiếp đến giao dịch, trừ khi chính sách chiến dịch quy định rõ cách tính khác.",
  "Bên A có quyền điều chỉnh mức hoa hồng/tỷ lệ chia sẻ theo từng thời kỳ để phù hợp với chính sách của sàn/đối tác, điều kiện thị trường, chi phí vận hành và quá trình phát triển của ShopTik. Mọi thay đổi phải được công bố hoặc thông báo cho Bên B trước thời điểm áp dụng và chỉ áp dụng đối với giao dịch/chuyển đổi phát sinh từ thời điểm chính sách mới có hiệu lực. Các giao dịch đã được ghi nhận hợp lệ trước thời điểm đó tiếp tục áp dụng mức cũ, trừ trường hợp sàn/đối tác hoặc pháp luật có điều chỉnh bắt buộc mang tính hồi tố.",
  "Chỉ Đơn hàng hợp lệ sau đối soát mới được tính hoa hồng cuối cùng. Số liệu từ hệ thống tracking của sàn/đối tác là căn cứ chính; Bên B có quyền gửi khiếu nại kèm bằng chứng nếu phát hiện sai lệch.",
  "Bên A thực hiện thanh toán trong vòng 15 ngày làm việc kể từ khi khoản hoa hồng tương ứng đã được sàn/đối tác xác nhận và thanh toán/cho phép rút cho Bên A, trừ khi Phụ lục quy định lịch khác.",
  "Ngưỡng thanh toán tối thiểu (nếu áp dụng): [……………… VNĐ]. Khoản chưa đạt ngưỡng được chuyển sang kỳ tiếp theo.",
  "Các khoản hoàn, hủy, gian lận, chargeback hoặc điều chỉnh từ sàn/đối tác có thể được khấu trừ vào kỳ hiện tại/kỳ sau nếu có chứng cứ đối soát.",
  "Mỗi Bên tự thực hiện nghĩa vụ thuế của mình. Khoản tiền Bên B thực nhận là số hoa hồng/tỷ lệ chia sẻ đã được xác nhận sau đối soát, sau khi trừ các khoản thuế phải khấu trừ tại nguồn, khoản Bên A phải kê khai/nộp thay và các khoản điều chỉnh hợp lệ theo pháp luật hoặc chính sách chiến dịch. Bên A có trách nhiệm cung cấp chứng từ hoặc thông tin khấu trừ/nộp thay cho Bên B khi pháp luật yêu cầu.",
  "ĐIỀU 8. NỘI DUNG, SỞ HỮU TRÍ TUỆ VÀ QUYỀN SỬ DỤNG HÌNH ẢNH",
  "8.1. Trừ tài liệu thuộc Bên A/đối tác, Bên B giữ quyền sở hữu trí tuệ đối với nội dung do Bên B tự sáng tạo. Bên B cam kết nội dung không xâm phạm quyền của bên thứ ba và đã có quyền sử dụng nhạc, hình ảnh, font, video, nhân vật hoặc tài sản xuất hiện trong nội dung.",
  "Bên B cấp cho Bên A quyền không độc quyền, miễn phí bản quyền để lưu trữ, hiển thị và đăng lại nội dung đã được Bên B đăng trong chiến dịch trên website/app/kênh mạng xã hội chính thức của Bên A trong thời hạn hợp tác và 12 tháng sau khi chiến dịch kết thúc, chỉ nhằm giới thiệu chiến dịch, Nền tảng hoặc kết quả hợp tác.",
  "Việc dùng nội dung của Bên B để chạy quảng cáo trả phí, whitelisting/Spark Ads, cắt ghép làm TVC hoặc khai thác ngoài phạm vi trên phải có chấp thuận riêng của Bên B và thỏa thuận về thời hạn/phí nếu có.",
  "Bên A không được sử dụng video xác minh khuôn mặt, ảnh CCCD/Thẻ căn cước hoặc dữ liệu eKYC của Bên B làm nội dung quảng cáo, nội dung công khai, huấn luyện mô hình AI hoặc nhận diện thương mại nếu chưa có sự đồng ý riêng, rõ ràng của Bên B.",
  "Bên A có quyền sử dụng tên hiển thị, avatar và đường dẫn kênh của Bên B trên danh sách đối tác/chiến dịch khi Bên B đã đồng ý tham gia chiến dịch công khai.",
  "ĐIỀU 9. BẢO MẬT THÔNG TIN",
  "Bên B không được tiết lộ cho bên thứ ba Thông tin mật của Bên A, bao gồm nhưng không giới hạn: tỷ lệ chia nội bộ chưa công khai, dữ liệu doanh thu/đơn hàng, cấu trúc tracking, danh sách đối tác, API, tài liệu kỹ thuật, kế hoạch sản phẩm, chiến dịch chưa công bố, dữ liệu người dùng và thông tin đàm phán thương mại.",
  "Bên A có nghĩa vụ tương tự đối với thông tin cá nhân, dữ liệu kênh, số liệu riêng, điều khoản thương mại riêng hoặc tài liệu chưa công khai của Bên B.",
  "Thông tin không được coi là mật nếu đã công khai hợp pháp; Bên nhận đã biết hợp pháp trước khi nhận; do bên thứ ba cung cấp hợp pháp; hoặc buộc phải cung cấp theo yêu cầu của cơ quan có thẩm quyền.",
  "Bên nhận chỉ được sử dụng Thông tin mật cho mục đích thực hiện Thỏa thuận, áp dụng biện pháp bảo mật phù hợp và chỉ chia sẻ cho nhân sự/nhà cung cấp cần biết có nghĩa vụ bảo mật tương ứng.",
  "Nghĩa vụ bảo mật có hiệu lực trong thời gian hợp tác và 03 năm sau khi chấm dứt; đối với bí mật kinh doanh/bí mật thương mại hoặc dữ liệu phải bảo vệ theo luật, nghĩa vụ kéo dài trong thời gian pháp luật yêu cầu hoặc cho đến khi thông tin hợp pháp trở thành công khai.",
  "Bên vi phạm phải chấm dứt hành vi, khắc phục hậu quả, hoàn trả/xóa tài liệu theo yêu cầu hợp pháp và bồi thường thiệt hại thực tế, hợp lý, có chứng cứ; phạt vi phạm chỉ áp dụng khi được ghi tại Phụ lục và trong giới hạn pháp luật cho phép.",
  "ĐIỀU 10. BẢO VỆ DỮ LIỆU CÁ NHÂN VÀ HỒ SƠ XÁC MINH",
  "Bên B xác nhận đã được thông báo và đồng ý để Bên A xử lý các dữ liệu cần thiết cho mục đích: xác minh danh tính/chủ tài khoản, phòng chống gian lận, quản lý hợp đồng, quản lý chiến dịch, đối soát, thanh toán, thuế, hỗ trợ và đáp ứng yêu cầu pháp lý.",
  "Dữ liệu có thể bao gồm: họ tên, ngày sinh, số và hình ảnh CCCD/Thẻ căn cước, địa chỉ, số điện thoại, email, tài khoản mạng xã hội, mã số thuế, tài khoản ngân hàng, lịch sử giao dịch/đối soát và video khuôn mặt xác minh.",
  "Video khuôn mặt và ảnh giấy tờ chỉ được truy cập bởi bộ phận/nhà cung cấp phục vụ xác minh, an ninh, pháp chế hoặc xử lý khiếu nại theo nguyên tắc cần biết; không được công khai.",
  "Bên A có thể sử dụng nhà cung cấp hạ tầng, lưu trữ, eKYC, thanh toán, kế toán/thuế hoặc chống gian lận với điều kiện có biện pháp bảo vệ dữ liệu và giới hạn mục đích phù hợp.",
  "Nếu dữ liệu được lưu trữ/xử lý ngoài Việt Nam, Bên A thực hiện các nghĩa vụ liên quan đến chuyển dữ liệu ra nước ngoài theo pháp luật hiện hành và thông báo/thu thập sự đồng ý khi pháp luật yêu cầu.",
  "Dữ liệu được lưu trong thời gian hợp tác và thời hạn cần thiết sau chấm dứt để hoàn thành đối soát, xử lý khiếu nại, phòng chống gian lận, đáp ứng nghĩa vụ thuế/kế toán/pháp lý; hết mục đích và thời hạn bắt buộc, dữ liệu phải được xóa, hủy hoặc ẩn danh theo quy trình của Bên A.",
  "Bên B có thể yêu cầu truy cập, chỉnh sửa, rút lại sự đồng ý hoặc thực hiện quyền khác theo pháp luật; việc rút lại sự đồng ý không làm mất tính hợp pháp của hoạt động xử lý đã thực hiện trước đó và có thể khiến Bên A không thể tiếp tục cung cấp một số chức năng cần xác minh danh tính.",
  "Khi xảy ra sự cố dữ liệu có khả năng ảnh hưởng đến Bên B, Bên A thực hiện ứng phó và thông báo theo phạm vi, thời hạn pháp luật yêu cầu.",
  "ĐIỀU 11. KIỂM DUYỆT, SỬA ĐỔI VÀ GỠ NỘI DUNG",
  "Đối với chiến dịch yêu cầu phê duyệt trước, Bên B chỉ được đăng sau khi nhận xác nhận của Bên A/nhãn hàng theo kênh được chỉ định.",
  "Bên A có quyền yêu cầu chỉnh sửa hoặc gỡ nội dung nếu nội dung sai thông tin, vi phạm pháp luật/chính sách nền tảng, chiến dịch đã kết thúc, sản phẩm bị thu hồi hoặc xuất hiện rủi ro đáng kể cho người tiêu dùng/thương hiệu.",
  "Trong trường hợp khẩn cấp liên quan đến pháp luật, an toàn người tiêu dùng, giả mạo hoặc xâm phạm dữ liệu, Bên B phải phối hợp ẩn/gỡ nội dung sớm nhất có thể, ưu tiên trong 24 giờ kể từ khi nhận thông báo hợp lệ.",
  "Nếu yêu cầu chỉnh sửa làm thay đổi đáng kể nội dung sáng tạo đã được phê duyệt và không xuất phát từ lỗi của Bên B, Các Bên sẽ thống nhất chi phí bổ sung (nếu có) trước khi thực hiện.",
  "ĐIỀU 12. THỜI HẠN, TẠM NGỪNG VÀ CHẤM DỨT",
  "Thỏa thuận có hiệu lực kể từ ngày ký điện tử/ký giấy hoặc ngày Bên B chấp nhận điều khoản trên Nền tảng và có thời hạn 12 (mười hai) tháng kể từ ngày có hiệu lực. Khi hết thời hạn, Thỏa thuận chấm dứt nếu Các Bên không có thỏa thuận gia hạn hoặc ký mới bằng văn bản, phương thức điện tử hoặc xác nhận trên Nền tảng. Việc hết hạn không làm mất hiệu lực của các nghĩa vụ đã phát sinh trước ngày hết hạn và các điều khoản được quy định tiếp tục có hiệu lực sau khi chấm dứt.",
  "Mỗi Bên có thể chấm dứt hợp tác thông thường bằng thông báo trước ít nhất 07 ngày, trừ chiến dịch đang có cam kết thời hạn riêng.",
  "Bên A có thể tạm ngừng/chấm dứt ngay nếu có bằng chứng hợp lý về gian lận, giả mạo, vi phạm pháp luật nghiêm trọng, xâm phạm dữ liệu, phát tán nội dung nguy hiểm hoặc hành vi có khả năng gây thiệt hại đáng kể cho người tiêu dùng/Nền tảng; Bên B có quyền yêu cầu Bên A cung cấp lý do và xem xét lại.",
  "Khi chấm dứt, Bên B ngừng sử dụng tài liệu mật, affiliate link hoặc dấu hiệu thương hiệu theo yêu cầu; Bên A tiếp tục đối soát và thanh toán các hoa hồng hợp lệ đã phát sinh trước ngày chấm dứt sau khi hoàn tất chu kỳ xác nhận/hoàn trả của sàn/đối tác.",
  "Các điều khoản về bảo mật, dữ liệu, sở hữu trí tuệ, thanh toán chưa hoàn tất, trách nhiệm và giải quyết tranh chấp tiếp tục có hiệu lực theo bản chất của chúng.",
  "ĐIỀU 13. TRÁCH NHIỆM VÀ BỒI THƯỜNG",
  "Mỗi Bên chịu trách nhiệm đối với hành vi, nội dung, tài liệu và cam kết do mình cung cấp hoặc tự tạo ra.",
  "Bên B chịu toàn bộ trách nhiệm pháp lý trong phạm vi hành vi và lỗi của mình nếu tự ý tạo, bổ sung, chỉnh sửa hoặc phát tán thông tin quảng cáo sai sự thật, gây nhầm lẫn hoặc vượt quá thông tin chính thức về sản phẩm/dịch vụ, bao gồm nhưng không giới hạn ở công dụng, chất lượng, xuất xứ, giá, ưu đãi, bảo hành, hoàn tiền hoặc điều kiện giao dịch; đồng thời chịu trách nhiệm nếu xâm phạm quyền của bên thứ ba, gian lận affiliate hoặc vi phạm quy định quảng cáo dù đã được Bên A cảnh báo/hướng dẫn.",
  "Bên B không được cố ý đăng tải, phát ngôn hoặc phát tán thông tin sai sự thật, xuyên tạc, vu khống, xúc phạm hoặc có hành vi trái pháp luật làm ảnh hưởng đến danh dự, uy tín, hình ảnh, thương hiệu của ShopTik/Bên A và các đối tác liên quan. Khi có vi phạm, Bên B phải chịu toàn bộ trách nhiệm pháp lý trong phạm vi hành vi và lỗi của mình; đồng thời phải phối hợp cải chính, gỡ bỏ hoặc khắc phục nội dung vi phạm trong thời hạn hợp lý theo yêu cầu hợp lệ của Bên A và bồi thường thiệt hại theo Thỏa thuận và pháp luật. Việc phản ánh, khiếu nại, đánh giá hoặc góp ý trung thực, có căn cứ và được thực hiện thiện chí theo đúng pháp luật không bị coi là hành vi bôi nhọ hoặc vi phạm điều khoản này.",
  "Bên A chịu trách nhiệm đối với thông tin do Bên A cung cấp hoặc phê duyệt nếu Bên B sử dụng đúng nội dung đó và không biết/không có căn cứ hợp lý để biết thông tin là sai.",
  "Trừ nghĩa vụ bắt buộc theo pháp luật, Bên A không phải là người bán/nhà sản xuất của sản phẩm bên thứ ba chỉ vì cung cấp công cụ affiliate; khi có khiếu nại sản phẩm, Bên A phối hợp chuyển tiếp thông tin và hỗ trợ trong phạm vi vai trò của mình.",
  "Bên gây thiệt hại phải bồi thường các thiệt hại trực tiếp, thực tế, hợp lý và có chứng cứ phát sinh từ hành vi vi phạm của mình, bao gồm chi phí hợp lý để xử lý khiếu nại, khắc phục nội dung, bảo vệ quyền và lợi ích hợp pháp của Bên bị thiệt hại theo quy định pháp luật. Nghĩa vụ bồi thường không loại trừ trách nhiệm hành chính, dân sự hoặc trách nhiệm pháp lý khác mà bên vi phạm phải tự chịu theo quy định.",
  "ĐIỀU 14. THÔNG BÁO VÀ GIAO KẾT ĐIỆN TỬ",
  "Thông báo có thể được gửi qua email, tài khoản Nền tảng, số điện thoại/Zalo đã đăng ký hoặc văn bản giấy theo thông tin liên hệ của Các Bên.",
  "Việc Bên B đánh dấu “Tôi đồng ý”, nhập OTP, ký điện tử, xác nhận trên Nền tảng hoặc tiếp tục tham gia sau khi đã được hiển thị đầy đủ điều khoản có thể được ghi nhận làm bằng chứng giao kết theo pháp luật về giao dịch điện tử và quy định liên quan.",
  "Mỗi Bên có trách nhiệm cập nhật thông tin liên hệ. Thông báo gửi đến thông tin gần nhất do Bên đó cung cấp được coi là đã gửi hợp lệ, trừ khi có bằng chứng hệ thống không thể chuyển phát.",
  "ĐIỀU 15. GIẢI QUYẾT KHIẾU NẠI VÀ TRANH CHẤP",
  "Khi phát sinh khiếu nại về đơn hàng/hoa hồng, Bên B gửi yêu cầu qua kênh hỗ trợ của Bên A kèm mã đơn, thời gian, link/nội dung liên quan và bằng chứng trong thời hạn chính sách công bố.",
  "Tranh chấp trước hết được giải quyết bằng thương lượng thiện chí trong vòng 30 ngày kể từ ngày một Bên thông báo tranh chấp.",
  "Nếu không giải quyết được bằng thương lượng, tranh chấp được đưa ra Tòa án có thẩm quyền theo pháp luật Việt Nam, trừ khi Các Bên có thỏa thuận trọng tài riêng bằng văn bản.",
  "ĐIỀU 16. ĐIỀU KHOẢN CHUNG",
  "Thỏa thuận này cùng Phụ lục, chính sách hoa hồng và Đơn đặt hàng chiến dịch (nếu có) tạo thành toàn bộ thỏa thuận liên quan đến phạm vi hợp tác tương ứng.",
  "Nếu có xung đột, thứ tự ưu tiên áp dụng là: (1) Phụ lục/Đơn đặt hàng chiến dịch ký riêng cho chiến dịch; (2) Thỏa thuận này; (3) chính sách vận hành công bố trên Nền tảng, trừ khi văn bản cấp cao hơn quy định khác.",
  "Việc sửa điều khoản cốt lõi về quyền sử dụng nội dung, dữ liệu cá nhân, tỷ lệ chia đã phát sinh hoặc nghĩa vụ thanh toán phải được thông báo rõ; không áp dụng hồi tố bất lợi cho Bên B nếu không có căn cứ pháp luật hoặc thỏa thuận riêng.",
  "Nếu một điều khoản bị xác định vô hiệu/không thể thi hành, các điều khoản còn lại vẫn có hiệu lực; Các Bên thay thế điều khoản đó bằng quy định hợp pháp gần nhất với mục đích ban đầu.",
  "Thỏa thuận được lập bằng tiếng Việt, có thể tồn tại dưới bản giấy hoặc bản điện tử và có giá trị như nhau theo pháp luật.",
  "PHỤ LỤC 01",
  "HỒ SƠ ĐĂNG KÝ & XÁC MINH KOL/KOC",
  "(Kèm theo Thỏa thuận hợp tác KOL/KOC số ……/2026/HT-KOLKOC)",
  "STT",
  "Hồ sơ/thông tin",
  "Nội dung Bên B cung cấp",
  "Kiểm tra",
  "1",
  "TikTok",
  "URL: ______________________________Tên tài khoản: _____________________",
  "☐",
  "2",
  "Facebook",
  "URL: ______________________________Tên trang/profile: __________________",
  "☐",
  "3",
  "YouTube",
  "URL: ______________________________Tên kênh: __________________________",
  "☐",
  "4",
  "CCCD/Thẻ căn cước - mặt trước",
  "Đính kèm ảnh rõ nét",
  "☐",
  "5",
  "CCCD/Thẻ căn cước - mặt sau",
  "Đính kèm ảnh rõ nét",
  "☐",
  "6",
  "Video khuôn mặt xác minh",
  "File/video 5–15 giây; khuôn mặt rõ; không filter che mặt",
  "☐",
  "7",
  "Mã số thuế cá nhân",
  "____________________________________",
  "☐",
  "8",
  "Tài khoản ngân hàng",
  "STK: _______________________________Ngân hàng: _________________________",
  "☐",
  "9",
  "Email / SĐT",
  "____________________________________",
  "☐",
  "10",
  "Nền tảng khác (nếu có)",
  "Instagram/Threads/Website/Khác: __________________",
  "☐",
  "XÁC NHẬN CỦA BÊN B VỀ DỮ LIỆU XÁC MINH",
  "☐ Tôi xác nhận các thông tin, link tài khoản, giấy tờ và video cung cấp là của tôi/hợp pháp và chính xác tại thời điểm đăng ký.",
  "☐ Tôi đồng ý để Bên A xử lý các dữ liệu trên cho mục đích xác minh danh tính, chống gian lận, quản lý hợp tác, đối soát, thanh toán, thuế, hỗ trợ và tuân thủ pháp luật theo Điều 10 của Thỏa thuận.",
  "☐ Tôi hiểu rằng ảnh CCCD/Thẻ căn cước và video khuôn mặt không được Bên A dùng cho quảng cáo, đăng công khai hoặc huấn luyện AI nếu chưa có sự đồng ý riêng của tôi.",
  "PHỤ LỤC 02",
  "THÔNG TIN CHIẾN DỊCH / HOA HỒNG",
  "Tên chiến dịch",
  "[……………………]",
  "Sàn/đối tác",
  "[Shopee/TikTok Shop/Lazada/Khác]",
  "Thời gian",
  "Từ ……/……/…… đến ……/……/……",
  "Kênh đăng",
  "[TikTok/Facebook/YouTube/Khác]",
  "Số lượng nội dung",
  "[……………………]",
  "Mức hoa hồng/tỷ lệ chia sẻ",
  "[……% / ………… VNĐ; cơ sở tính và khấu trừ thuế theo Điều 7]",
  "Điều kiện ghi nhận",
  "[Theo dashboard/chính sách chiến dịch]",
  "Lịch đối soát/thanh toán",
  "[……………………]",
  "Yêu cầu đặc biệt",
  "[……………………]",
  "XÁC NHẬN VÀ CHỮ KÝ CÁC BÊN",
  "ĐẠI DIỆN BÊN A",
  "(Ký, ghi rõ họ tên; đóng dấu nếu có)",
  "Họ tên: __________________________",
  "BÊN B – KOL/KOC",
  "(Ký, ghi rõ họ tên)",
  "Họ tên: __________________________",
  "Lưu ý sử dụng: Đây là mẫu thỏa thuận khung. Trước khi phát hành chính thức, cần điền đầy đủ thông tin pháp nhân, MST, người đại diện, ngưỡng/lịch thanh toán, kênh hỗ trợ và chính sách chiến dịch; nên được bộ phận pháp chế/luật sư rà soát theo mô hình vận hành thực tế của doanh nghiệp."
];

/**
 * Bản CHỈ ĐỂ ĐỌC hiển thị ở bước 1: giữ phần mở đầu (quốc hiệu, tiêu đề, căn cứ)
 * và toàn bộ các ĐIỀU khoản; LƯỢC BỎ bảng thông tin Bên A/Bên B và các Phụ lục
 * vì đó chỉ là khung có ô trống để điền — không phải nội dung để người dùng đọc.
 * Thông tin Bên B điền ở bước 2, Bên A do admin điền khi duyệt (in vào PDF).
 */
function buildDisplayParagraphs(): string[] {
  const all = KOL_AGREEMENT_PARAGRAPHS;
  const partyStart = all.findIndex((p) => p.startsWith("Hôm nay, ngày"));
  const clauseStart = all.findIndex((p) =>
    p.startsWith("Bên A và Bên B sau đây gọi riêng"),
  );
  const appendixStart = all.findIndex((p) => p === "PHỤ LỤC 01");
  if (partyStart < 0 || clauseStart <= partyStart || appendixStart <= clauseStart) {
    return [...all];
  }
  return [
    ...all.slice(0, partyStart),
    ...all.slice(clauseStart, appendixStart),
  ].filter((p) => !p.startsWith("Số:"));
}

export const KOL_AGREEMENT_DISPLAY: readonly string[] = buildDisplayParagraphs();
